# server encoding
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  # h2 db driver setting
  datasource:
    url: jdbc:h2:mem:jakedb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # jpa setting
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create #create, update, none
      naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true