# server encoding
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
#  # h2 db driver setting
#  datasource:
#    url: jdbc:h2:mem:jakedb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: jake
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa setting
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #create, update, none
      naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  # oauth setting
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 255229286046-hattfsnn2mqqhd72q96ms0rc64k7g2ev.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

